Add wb adapters
black-parrot-hdk/black-parrot-subsystems pull request #10
Opened 2022-09-17 12:26 UTC by T-Platz

This PR adds BP <-> WB adapters.

2022-09-19 23:55 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +    state = WAIT_CMD;
don't use initial, explicitly reset all registers

2022-09-19 23:56 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +      unique case (1'b1)
what's this?

2022-09-19 23:59 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +    mem_cmd_header_cast_o.msg_type       = addr >= cached_addr_base_lp
just use uc_wr/uc_rd and eschew the cached_addr_base_lp logic.  wr/rd are intended to be used for cached fill operations while these adapters are only I/O

2022-09-19 23:59 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +      ? (we_i ? e_bedrock_mem_wr    : e_bedrock_mem_rd)     // ? 1 : 0
Don't comment with real values, these should be able to change transparently

2022-09-20 00:01 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +  bsg_dff_reset_en
Use bsg_one_fifo and pop when requests come back. This will scale better for having multiple outstanding requests in the future

2022-09-20 00:01 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +    , localparam wbone_data_width_lp = 64
just use data_width_p

2022-09-20 00:01 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +    , localparam cached_addr_base_lp = 32'h8000_0000
get rid of wbone_addr_ubound, wbone_addr_lbound, wbone_addr_width_lp, cached_addr_base_lp as discussed below

2022-09-20 00:04 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +      mem_cmd_v_o <= 0;
Use a two process FSM like seen here: https://github.com/black-parrot-hdk/black-parrot-subsystems/blob/9e64c62c11d220c844fb40609ee39cff1bacd704/axi/v/bp_me_axil_to_burst.sv#L222

always_comb for signals and state_n decision

always_ff for state_r <= state_n

2022-09-20 00:04 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +  bp_bedrock_msg_size_e msg_size;
Add an assertion that addresses are aligned

2022-09-20 00:05 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +      8'h01:
Believe this logic can be encompassed in bsg_priority_encode

2022-09-20 00:06 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +      ,.size_i(msg_size[1:0])
This slice only works for 64b, calculate the slice needed for abitrary widths

2022-09-20 00:06 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +  logic [uce_fill_width_p-1:0] mem_resp_data_li;
use data_width_p and assume input == output width

2022-09-20 00:08 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +  bsg_dff_reset_en
Actually, not sure why this is necessary at all. Can't we drive the wishbone data response directly from mem_resp_data_i?

2022-09-20 00:08 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +  bsg_dff_reset_en
mem_resp_header_li is not used

2022-09-20 00:09 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +        state[1]:
If you're using a case, use e_state as the label, not specific bits

2022-09-20 00:10 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> + * DESCRIPTION: THIS MODULE ADAPTS BP MEMORY BUS TO 64-BIT WISHBONE FOR CLIENT DEVICES
Use regular case for comments, and this module should support 32 or 64b at least. I would just drop the 64-BIT qualifier

2022-09-20 00:10 UTC, dpetrisko commented on wb/test/bp_me_wb_loopback.sv
> +    // Slave BP
Client

2022-09-20 00:10 UTC, dpetrisko commented on wb/test/bp_me_wb_loopback.sv
> +    // Slave BP
(throughout)

2022-09-20 00:11 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> + * DESCRIPTION: THIS MODULE ADAPTS BP MEMORY BUS TO 64-BIT WISHBONE FOR MASTER DEVICES
Same comments as client header

2022-09-20 00:12 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +    , localparam wbone_addr_ubound   = paddr_width_p
Same comments as client

2022-09-20 00:12 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +  always_ff @(posedge clk_i) begin
two process FSM

2022-09-20 00:12 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +        state[0]:
use e_state explicitly

2022-09-20 00:13 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +      unique case (1'b1)
?

2022-09-20 00:13 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +  bp_bedrock_mem_header_s mem_cmd_header_li;
Use bsg_one_fifo, enqueue on message out and dequeue on message back. This will scale better to multiple outstanding requests

2022-09-20 00:14 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +    // dat_o
comment doesn't add anything

2022-09-20 00:14 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +    // adr_o
comment doesn't add anything

2022-09-20 00:15 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +      ? '1
don't need a ternary

2022-09-20 00:16 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> + */
`include "bp_common_defines.svh"
`include "bp_me_defines.svh"

2022-09-20 00:17 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +
`include "bp_common_defines.svh"
`include "bp_me_defines.svh"

2022-09-20 00:17 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +    , input  [7:0]                           sel_i
calculate

2022-09-20 00:17 UTC, dpetrisko commented on wb/v/bp_me_wb_master.v
> +    , output logic [7:0]                     sel_o
calculate

2022-09-20 00:19 UTC, dpetrisko commented on wb/test/sim_main.cpp
> +        dut->c_mem_cmd_ready_i = 1;
Seems like this is missing backpressure cases such as back to back writes or reads without acknowledgements

2022-09-20 00:20 UTC, dpetrisko requested changes
Good start! Left feedback for the hardware primarily, but the testbench I think needs work to exercise the handshakes properly

2022-09-22 10:10 UTC, T-Platz commented on wb/v/bp_me_wb_client.v
> +  bsg_dff_reset_en
On driving the WB data directly from the BP signals: Since the adapter introduces a latency of one cycle, wouldn't it then be possible that the mem_resp_data_i is only valid exactly when mem_resp_v_i is high and when I set ack_o one cycle later, mem_resp_data_i is something different and so the adapter's response would be wrong?

2022-09-22 10:12 UTC, T-Platz commented on wb/v/bp_me_wb_client.v
> +    , localparam wbone_data_width_lp = 64
I don't really know what exactly you mean by data_width_p. I only found bedrock_data_width_p, or do you mean something like [this](https://github.com/black-parrot-hdk/black-parrot-subsystems/blob/main/axi/v/bp_me_axil_master.sv#L16)?

2022-09-22 10:17 UTC, T-Platz commented on wb/v/bp_me_wb_client.v
> +    , input  [7:0]                           sel_i
What exactly do you mean here?

2022-09-22 10:36 UTC, T-Platz commented on wb/v/bp_me_wb_client.v
> +      ,.size_i(msg_size[1:0])
What exactly do you mean by "calculate the slice"? And should this not also work for 32b data in and data out?

2022-09-22 10:38 UTC, T-Platz commented on wb/v/bp_me_wb_client.v
> + * DESCRIPTION: THIS MODULE ADAPTS BP MEMORY BUS TO 64-BIT WISHBONE FOR CLIENT DEVICES
Does supporting 32b also mean 32b to 64b conversion and vice versa or only 32b to 32b and 64b to 64b?

2022-09-22 15:07 UTC, T-Platz commented on wb/v/bp_me_wb_client.v
> +  bp_bedrock_msg_size_e msg_size;
Shouldn't this assertion be placed in the master adapter, because only there I know the last three bits of the address specified in the original command?

2022-09-22 15:08 UTC, T-Platz commented on wb/v/bp_me_wb_client.v
> +      8'h01:
I managed to strip this part down so that I can basically copy the code from [here](https://github.com/black-parrot-hdk/black-parrot-subsystems/blob/9e64c62c11d220c844fb40609ee39cff1bacd704/axi/v/bp_me_axil_to_burst.sv#L118). Does that suffice as well?

2022-09-22 19:27 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +    , localparam wbone_data_width_lp = 64
I'm suggesting to have a single parameter called data_width_p

2022-09-22 19:28 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +    , input  [7:0]                           sel_i
no magic numbers. 8 is only valid for 64b width

2022-09-22 19:29 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +      8'h01:
yeah that's fine

2022-09-22 19:30 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +  bp_bedrock_msg_size_e msg_size;
Assertions are there to noisily complain if an unexpected condition happens that will break the hardware.  If this module receives a misaligned address, it will have undefined behavior and we want to notify the user

2022-09-22 19:32 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +      ,.size_i(msg_size[1:0])
if the data width was 16b, this code would not compile.  The size is related to the maximum width of the data in bytes

2022-09-22 19:34 UTC, dpetrisko commented on wb/v/bp_me_wb_client.v
> +  bsg_dff_reset_en
The mem_resp transaction will only be completed when mem_resp_v_i & mem_resp_ready_and_o. So if the adapter cannot handle mem_resp_v_i in a specific cycle, then mem_resp_ready_and_o should be lowered. mem_resp_data_i is only valid when mem_resp_v_i is high

2022-09-29 21:40 UTC, dpetrisko requested changes
Good progress!

2022-09-29 21:40 UTC, dpetrisko commented on wb/test/sv/bp_me_wb_loopback.sv
> +    );
Make assertions that the address widths are what you expect here. The C++ code only works for a very specific BP configuration

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +    , parameter data_width_p         = (cce_type_p == e_cce_uce) ? uce_fill_width_p : bedrock_data_width_p
parameter data_width_p = dword_width_gp

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +      default: ;
default: begin end

If you use unique case, this is required to avoid simulation/synthesis mismatches

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +  // advance to next state
// synopsys sync_set_reset "reset_i"
always_ff @(posedge clk_i)

Needed for synthesis

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +        cyc_o = mem_cmd_v_i & mem_cmd_ready_o & !reset_i;
This is out of sync.

mem_cmd_header_lo is the output of the fifo, but mem_cmd_v_i/mem_cmd_ready_o are the input to the fifo. So the header comes a cycle after the valids go high.  Instead, need to use the fifo outputs for everything i.e. cyc_o = mem_cmd_v_li;

I would double check that your testbench code is correctly implementing the wishbone spec

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +        stb_o = mem_cmd_v_i & mem_cmd_ready_o & !reset_i;
Implement an explicit reset state rather than directly using the signal

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +    mem_resp_yumi_o = 1'b0;
mem_resp_yumi_o can be mem_resp_ready_o since it is only dependent on state

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +        state_n = cyc_i & stb_i
What is the difference between CYC and STB? Can one be high without the other?

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +    mem_cmd_header_cast_o.addr           = {adr_i, 3'b000};
are these signals guaranteed to be constant during the transaction?

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +      e_send_cmd: begin
Do we need this state? Can't we send directly from e_wait_cmd

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +      e_wait_resp: begin
Not sure if we need this state either. If we're guaranteed that WB will wait on the transaction until ack, we can just directly drive ACK by mem_resp_v_i

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +      default: ;
default: begin end as below

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +  // advance to next state
// synopsys sync_set_reset "reset_i"
always_ff @(posedge clk_i)

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +    , parameter data_width_p         = (cce_type_p == e_cce_uce) ? uce_fill_width_p : bedrock_data_width_p
data_width_p = dword_width_gp

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> + *  This module converts BlackParrot (BP) Bedrock commands to Wishbone (WB) for client devices
Link the WB spec here

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> + *  This module converts BlackParrot (BP) Bedrock commands to Wishbone (WB) for master devices
Link the WB spec here

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +     ,.ready_o()
Use the ready as a condition for sending out the request to WB. That will guarantee that there's space in the FIFO in future

2022-09-29 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +     ,.v_i(mem_cmd_v_i & mem_cmd_ready_o)
just v_i is fine, the interface is ready & valid

2022-10-01 15:00 UTC, T-Platz commented on wb/v/bp_me_wb_client.sv
> +        state_n = cyc_i & stb_i
cyc == 1 means that the bus is used, while stb == 1 means that signals like adr and dat are valid. With standard WB, the two signals are always the same. The WB spec then even allows using the same signal for cyc and stb, however, both signals must still be present in the interface (Observation 3.55 and Illustrations 3-5 and 3-7 in the specification). So I could just use cyc or stb in this case, but it somehow feels wrong and the specification also says that an ack must be generated in response to the product of cyc and stb.

2022-10-01 15:02 UTC, T-Platz commented on wb/v/bp_me_wb_client.sv
> +    mem_cmd_header_cast_o.addr           = {adr_i, 3'b000};
If I understood Illustrations 3-5 and 3-7 correctly, then yes.

2022-10-01 15:30 UTC, T-Platz commented on wb/v/bp_me_wb_master.sv
> +        cyc_o = mem_cmd_v_i & mem_cmd_ready_o & !reset_i;
I'm not using the fifo's output to drive the WB "header" signals like adr and sel. Instead, I'm directly using the modules mem_cmd_header_i and mem_cmd_data_i, so I'm not dependent on when the fifo's output is valid.

2022-10-01 15:36 UTC, T-Platz commented on wb/v/bp_me_wb_master.sv
> +        cyc_o = mem_cmd_v_i & mem_cmd_ready_o & !reset_i;
Although, I just realized that this implementation might then not fulfill the below mentioned requirement that the WB signals must be valid during WB transfer. The master adapter's BP inputs might change after the ready-valid-handshake and so would the WB signals.

So I believe I'd have to store the command's header and data in two fifos and then use their valid outputs to drive the cyc and stb signals, right?

2022-10-01 21:10 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +        state_n = cyc_i & stb_i
So for multiple clients, the bus may raise cyc for both clients and stb for only one? Makes sense

2022-10-01 21:14 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +    , parameter data_width_p         = (cce_type_p == e_cce_uce) ? uce_fill_width_p : bedrock_data_width_p
unresolved

2022-10-01 21:14 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +    mem_resp_yumi_o = 1'b0;
unresolved

2022-10-01 21:16 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +    mem_cmd_header_cast_o.addr           = {adr_i, 3'b000};
Hmm, would feel better if we can find a guarantee in the spec. Otherwise, it's safer to latch inputs during transactions as in AXI. At the least, we'll need a $stable assertion to raise an error if this assumption is violated

2022-10-01 21:16 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +      default: ;
unresolved

2022-10-01 21:17 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +  // advance to next state
unresolved

2022-10-01 21:17 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> + *  This module converts BlackParrot (BP) Bedrock commands to Wishbone (WB) for master devices
unresolved

2022-10-01 21:17 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +    , parameter data_width_p         = (cce_type_p == e_cce_uce) ? uce_fill_width_p : bedrock_data_width_p
unresolved

2022-10-01 21:17 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +     ,.v_i(mem_cmd_v_i & mem_cmd_ready_o)
unresolved

2022-10-01 21:18 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +        cyc_o = mem_cmd_v_i & mem_cmd_ready_o & !reset_i;
yep

2022-10-01 21:18 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +        cyc_o = mem_cmd_v_i & mem_cmd_ready_o & !reset_i;
header and data can be in a single fifo, though

2022-10-01 21:19 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +      default: ;
unresolved

2022-10-01 21:19 UTC, dpetrisko commented on wb/v/bp_me_wb_master.sv
> +  // advance to next state
unresolved

2022-10-01 21:19 UTC, dpetrisko commented
Hi, please don't resolve comments unless the feedback is addressed

2022-10-01 21:40 UTC, dpetrisko commented on wb/v/bp_me_wb_client.sv
> +    mem_cmd_header_cast_o.addr           = {adr_i, 3'b000};
> i_wb_stb is true for any bus transaction request. While i_wb_stb is true, the other wishbone slave inputs (i_wb_we, i_wb_addr, i_wb_data, and i_wb_sel) are valid and reference the same transaction. The transaction is accepted by the slave any time i_wb_stb is true at the same time as o_wb_stall is false.

Found this here: https://zipcpu.com/zipcpu/2017/05/29/simple-wishbone.html

Good enough for me, we can assume that STB implies the same transaction until ACK

2022-10-02 12:57 UTC, T-Platz commented on wb/v/bp_me_wb_client.sv
> +        state_n = cyc_i & stb_i
Exactly. When using pipelined mode for example, there can also be cycles when cyc is high and stb is low and the client shall not respond.

2022-10-03 13:21 UTC, T-Platz commented on wb/v/bp_me_wb_client.sv
> +      e_send_cmd: begin
Indeed, this state can be removed.

2022-10-03 13:22 UTC, T-Platz commented on wb/v/bp_me_wb_client.sv
> +      e_wait_resp: begin
I've tried getting rid of the state machine completely, but the problem is that cyc_i and stb_i will both be set until the master adapter receives the response. When using mem_cmd_v_o = cyc_i & stb_i, the client might interpret a single transaction as multiple commands, since v_o will not be reset after the handshake. So you need some way of storing the information whether the current WB command has already been forwarded to the client and I believe this is a rather simple and clear approach.

2023-01-18 13:48 UTC, T-Platz commented
Request review. Short note:
The master adapter assumes a maximum message size of cce_block_width_p. This parameter is forwarded to the stream pumps used in the master adapter and controls the pumps' output. Messages larger than that will not be processed correctly. This can be tested for example by assigning a constant 7 to the command size during command generation [here](https://github.com/T-Platz/black-parrot-subsystems/blob/wb_adapters/wb/test/cpp/bp_me_wb_master_ctrl.cpp#L27), resulting in 1024 bit commands, while the cce block width should be 512 with the default BP config.

2023-01-20 21:59 UTC, dpetrisko commented on wb/sv/bp_me_wb_client.sv
> +        ack_o = mem_fwd_v_o & mem_fwd_ready_and_i
I think we want to wait for responses for both writes and reads to avoid possible reorderings in the network, since wishbone does not support transaction IDs.

So the logic would just be to always transition to wait until mem_rev_v_i is received

2023-01-20 22:00 UTC, dpetrisko commented on wb/sv/bp_me_wb_client.sv
> +    state_r <= reset_i
```
if (reset_i)
  state_r <= e_reset
else
  state_r <= state_n;
```

More likely to synthesize properly

2023-01-20 22:01 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +  logic [mem_rev_header_width_lp-1:0] return_fifo_header_o;
_lo / _li for local signals

2023-01-20 22:02 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +    state_r <= reset_i
```
if (reset_i)
  state_r <= e_reset
else
  state_r <= state_n;
```

More likely to synthesize properly

2023-01-20 22:04 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = mem_fwd_v_li & mem_rev_ready_and_li;
Why do we latch these instead of drive directly?

2023-01-20 22:04 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +      e_wait_cmd: begin
e_wait_cmd -> e_ready

2023-01-20 22:07 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = ~ack_i;
Maybe I'm misunderstanding, but this state seems unnecessary. Is the logic simply hold cyc_n/stb_n until ack? If so, that's the same logic as e_wait_cmd? What is different between them?

2023-01-21 01:38 UTC, T-Platz commented on wb/sv/bp_me_wb_client.sv
> +        ack_o = mem_fwd_v_o & mem_fwd_ready_and_i
This is what we have talked about before. The reason why we have to ack writes immediately is the combination of the following two behaviors:
1. The BP client will only send a response to a write command when the last packet of data has arrived.
2. The WB master (e.g. the master adapter) will only send further data after receiving an ack.
So if we didn't ack the write immediately, the BP client would wait for further data, but the WB master would wait for an ack, resulting in a deadlock.

2023-01-21 01:38 UTC, T-Platz commented on wb/sv/bp_me_wb_client.sv
> +    state_r <= reset_i
Changed

2023-01-21 01:38 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +  logic [mem_rev_header_width_lp-1:0] return_fifo_header_o;
Changed

2023-01-21 01:38 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +    state_r <= reset_i
Changed

2023-01-21 01:38 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = mem_fwd_v_li & mem_rev_ready_and_li;
The client may drive ack directly off cyc&stb, so we need to do this to avoid cyclic dependencies, as cyc depends on ack in the master.

2023-01-21 01:38 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +      e_wait_cmd: begin
Changed

2023-01-21 01:38 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = ~ack_i;
You're kind of true, actually. While section 3.3.1 of the [WB spec](https://cdn.opencores.org/downloads/wbspec_b4.pdf) tells us we need a wait state (i.e. `stb == 0`) after an ack, we can achieve that by simply adding `~ack_i` as condition to rising `cyc` and `stb` in the wait_cmd state. In fact, we only need to do that with `stb`, so `cyc` can actually stay asserted as long as there is data to send.
In summary, removing the state machine, but only rising `stb` when `~ack` works.

2023-01-31 23:35 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +  logic [mem_rev_header_width_lp-1:0] return_fifo_header_o;
oh I don't see the change, is GitHub being weird?
```
logic [mem_rev_header_width_lp-1:0] return_fifo_header_o;
```

2023-01-31 23:37 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = ~ack_i;
yeah I would suggest that then, simplifies the logic signficantly

2023-01-31 23:38 UTC, dpetrisko commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = mem_fwd_v_li & mem_rev_ready_and_li;
Oh, I'm missing the cycle. cyc/stb->ack->yumi_i of the stream pump. But that's a fifo, so that should break the path. Is there another path I'm not considering?

2023-01-31 23:40 UTC, dpetrisko commented on wb/sv/bp_me_wb_client.sv
> +        ack_o = mem_fwd_v_o & mem_fwd_ready_and_i
For the client, aren't all messages 1 beat since wishbone is always 64b?

2023-02-01 15:15 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +  logic [mem_rev_header_width_lp-1:0] return_fifo_header_o;
I think GitHub is being weird, as in my code locally and in [my fork](https://github.com/T-Platz/black-parrot-subsystems/blob/wb_adapters/wb/sv/bp_me_wb_master.sv#L122) it says `_lo`.

2023-02-01 15:22 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = mem_fwd_v_li & mem_rev_ready_and_li;
The cycle I'm talking about is stb->ack->stb. In the master adapter, stb is dependent on ack and ack in the client adapter is dependent on stb.
Also, in the [WB spec](https://cdn.opencores.org/downloads/wbspec_b4.pdf) on page 40 for instance, it says that cyc and stb should stay asserted for another cycle after receiving the ack. Clearing stb immediately upon receiving the ack would violate this requirement I believe.

2023-02-01 15:23 UTC, T-Platz commented on wb/sv/bp_me_wb_master.sv
> +        cyc_n = ~ack_i;
Alright, removed the state machine.

2023-02-01 15:32 UTC, T-Platz commented on wb/sv/bp_me_wb_client.sv
> +        ack_o = mem_fwd_v_o & mem_fwd_ready_and_i
Yes, the messages leaving the client adapter are 64b at max (WB also supports messages smaller than bus width), but my thought process was that maybe some other component, like a cache controller, might still wait for all 512b to arrive before sending a response. Though I don't know whether this behavior would actually make sense and not violate the BP protocol. What are your thoughts on this?

2023-02-01 20:16 UTC, dpetrisko commented on wb/sv/bp_me_wb_client.sv
> +        ack_o = mem_fwd_v_o & mem_fwd_ready_and_i
For BP, the first ACK is entirely dependent on the message size being transmitted fully. 

Basically the issue would come up if 
- WB sent a 512b burst in 64b chunks
- that was translated to a 512b BP store
- WB expects 1 ACK after every beat

I don't believe we need to worry about that since we're only handling the single beat WB case. In our usage, we expect wishbone to send 8x64b independent writes instead

2023-02-17 03:56 UTC, dpetrisko commented
Thanks looks good to me!

2023-02-17 03:57 UTC, merged