[WIP] Adding axi lite top
black-parrot-hdk/black-parrot-subsystems pull request #11
Opened 2022-10-13 19:35 UTC by dpetrisko

This is a version of BP which is AXI-lite master only.  TODO: Make single AXI bus configuration option by having internal crossbar

2022-10-14 19:44 UTC, flaviens requested changes
Apart from these tiny minors, it seems to work like a charm, thank you! :+1:

2022-10-14 19:44 UTC, flaviens commented on axi/v/bp_axi_lite_top.sv
> +     ,.mem_fwd_header_o(proc_fwd_header_lo)
A little typo here, should probably be

```
     ,.mem_cmd_header_o(proc_fwd_header_lo)
     ,.mem_cmd_data_o(proc_fwd_data_lo)
     ,.mem_cmd_v_o(proc_fwd_v_lo)
     ,.mem_cmd_ready_and_i(proc_fwd_ready_and_li)
     ,.mem_cmd_last_o(proc_fwd_last_lo)

     ,.mem_resp_header_i(proc_rev_header_li)
     ,.mem_resp_data_i(proc_rev_data_li)
     ,.mem_resp_v_i(proc_rev_v_li)
     ,.mem_resp_ready_and_o(proc_rev_ready_and_lo)
     ,.mem_resp_last_i(proc_rev_last_li)
```

2022-10-14 19:44 UTC, flaviens commented on axi/v/bp_axi_lite_top.sv
> +
Here probably this line is missing
```
  `declare_bp_cfg_bus_s(vaddr_width_p, hio_width_p, core_id_width_p, cce_id_width_p, lce_id_width_p);
```

2022-10-14 19:44 UTC, flaviens commented on axi/v/bp_axi_lite_top.sv
> +   , input                                      m_axil_awready_i
[1:0] missing here apparently

2022-12-10 02:43 UTC, dpetrisko commented
Hi @flaviens sorry for the delay! I have identified the burst issue with the AXI lite top. There is a minor fix I’ll try to get to in the next week. I’ll let you know when it’s updated and I’d appreciate you trying it out!

2022-12-16 12:02 UTC, flaviens commented
Cool! Does this relate to [that issue](https://github.com/black-parrot/black-parrot/issues/1140)?

2022-12-16 18:10 UTC, dpetrisko commented
Yep same issue!

2023-01-11 16:27 UTC, flaviens commented
Sounds cool, as soon as you have it, I'll try to give you feedback!

2023-02-02 13:38 UTC, dpetrisko commented
@flaviens Sorry for the delay again! I've updated the AXIL master to handle bursts properly, which should 🤞 fix the issue that you're seeing

2023-02-02 13:40 UTC, dpetrisko commented on axi/v/bp_axi_lite_top.sv
> +
fixed!

2023-02-02 13:40 UTC, dpetrisko commented on axi/v/bp_axi_lite_top.sv
> +   , input                                      m_axil_awready_i
fixed!

2023-02-17 10:35 UTC, flaviens requested changes

2023-02-17 10:35 UTC, flaviens commented on axi/v/bp_axi_lite_top.sv
> +  bp_bedrock_mem_header_s [1:0] proc_fwd_header_lo;
This is probably intended to be `bp_bedrock_mem_fwd_header_s`, and same some lines below should be `bp_bedrock_mem_rev_header_s` probably

2023-02-17 10:35 UTC, flaviens commented on axi/v/bp_axi_lite_top.sv
> +         ,.io_cmd_header_i(proc_fwd_header_lo[i])
This interface should also be updated:

         ,.mem_fwd_header_i(proc_fwd_header_lo[i])
         ,.mem_fwd_data_i(proc_fwd_data_lo[i])
         ,.mem_fwd_v_i(proc_fwd_v_lo[i])
         ,.mem_fwd_last_i(proc_fwd_last_lo[i])
         ,.mem_fwd_ready_and_o(proc_fwd_ready_and_li[i])

         ,.mem_rev_header_o(proc_rev_header_li[i])
         ,.mem_rev_data_o(proc_rev_data_li[i])
         ,.mem_rev_v_o(proc_rev_v_li[i])
         ,.mem_rev_last_o(proc_rev_last_li[i])
         ,.mem_rev_ready_and_i(proc_rev_ready_and_lo[i])

2023-02-17 13:36 UTC, flaviens commented
Hi Dan,

Thank you very much for the fixes!
Indeed the problem disappears.
However, I still have issues running simple code. If the first instruction is an infinite look it runs fine, but as soon as I add some nops before the infinite loop, the CPU ends up jumping to address 0.
Have you also observes such behaviors?
Thanks!
Flavien

2023-02-19 16:47 UTC, flaviens commented
I dug a bit more into the waveforms. The observation is the following:
- The bursts are 8 instructions long but in a single burst, the address does not change (the exact same 2 instructions (64 bits)) are fetched 8 times in a row. Apparently only the first of two instruction is executed.
- Once a fetch burst is done, the PC increases by 0x40, so apparently 7 of 8 instructions are ignored.

I made a quick experiment where I inserted 7 nops after each instruction. It does not run perfectly, but apparently it already ran some instructions.

Let me know if I can help.

2023-05-21 10:21 UTC, flaviens commented
Hi Dan, thanks for the update! Is the branch ready for a retry already?

2023-05-22 21:44 UTC, dpetrisko commented
>Hi Dan, thanks for the update! Is the branch ready for a retry already?

Yep! Think this should be good to go

2023-05-28 09:45 UTC, flaviens commented
Thanks! I'm having some difficulties with the parametrization (the repo defines are unfortunately inadapted to search by name). Specifically, I'm stumbling into the error ` data width and Bedrock fill width must match (probably 64b).`, where AXI Lite width is 64 bits but Bedrock width is 128. How to set the bedrock fill width to the correct value properly?

2023-06-19 04:49 UTC, dpetrisko commented
Sorry @flaviens that's a spurious warning! We support different fill widths, I've removed the warning (make sure to update to latest BP to ensure compatibility)

2023-07-18 06:04 UTC, dpetrisko commented
I'm pretty sure this should work, so I'm going to go ahead and merge as part of housekeeping. Please keep me posted if you discover anymore issues @flaviens !

2023-07-18 06:04 UTC, merged