async AXI support
black-parrot-hdk/black-parrot-subsystems pull request #17
Opened 2022-12-20 19:14 UTC by mysoreanoop

TODOs depend on how the adapters will implement burst-support.
Can discuss asynchronously for syncing up implementations

2022-12-20 19:31 UTC, dpetrisko commented
Hi, no need to delete and open new PRs. It's easier to keep track if you push to the original PR

2022-12-20 19:44 UTC, mysoreanoop commented
Yeah sorry, there were no reviews/comments; since there were also intermediate unmergeable commits, this was easier.

2022-12-20 20:06 UTC, dpetrisko requested changes

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
>    (input                                       clk_i
aclk_i/areset_i are axi clk name conventions. 

should be aclk_i/areset_i+bp_clk_i/bp_reset_i

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> +  wire axi_clk_li   = ((cce_type_p == e_cce_uce) && axi_async_p) ? aclk_i   : clk_i;
don't check cce_type for this clock switch, assert that axi_async_p == 0 || cce_type_p == e_cce_uce

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> -        ,.mem_fwd_header_o(mem_fwd_header_lo)
maintain the same formatting

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> +        ,.mem_rev_ready_and_i (~bp_resp_ready_and_li)
bp_resp_ready_and_li = fifo_full_li. As written, very confusing

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> +      bp_bedrock_mem_fwd_header_s bp_cmd_header_lo;
cmd->fwd
resp->rev

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> -        ,.mem_fwd_header_o(mem_fwd_header_lo)
throughout

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> +              // TODO these work with the current AXI burst scenario;
what is the concern here?

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> +      assign bp_dma_pkt_ready_and_li   = ~c2a_dma_pkt_ready_and_lo; // inverted at source
signals should always reflect their names

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> -    cache2axi
maintain formatting

2022-12-20 20:06 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> +        (.clk_i               (axi_clk_li)
let's push the async fifos into the axil client+master, so pass through aclk_i/areset_i and have the conversion in there. This will be useful for when we have multiple axi toplevels and don't need to replicate the crossing logic everywhere

2022-12-20 20:12 UTC, mysoreanoop commented on axi/v/bp_axi_top.sv
> +        ,.mem_rev_ready_and_i (~bp_resp_ready_and_li)
Do we change it to _full or keep it as is for uniformity between async and sync implementations?

2022-12-20 20:12 UTC, mysoreanoop commented on axi/v/bp_axi_top.sv
> +      bp_bedrock_mem_fwd_header_s bp_cmd_header_lo;
Oops yeah, I think I missed a commit, will fix it

2022-12-20 20:33 UTC, mysoreanoop commented on axi/v/bp_axi_top.sv
> -    cache2axi
You mean the spacing before "("?

2023-01-03 04:43 UTC, mysoreanoop commented on axi/v/bp_axi_top.sv
>    (input                                       clk_i
Got it, retained clk_i, used aclk_i for AXI anyway; changed the synthesis directive.

2023-01-03 04:45 UTC, mysoreanoop commented on axi/v/bp_axi_top.sv
> +      assign bp_dma_pkt_ready_and_li   = ~c2a_dma_pkt_ready_and_lo; // inverted at source
The reasoning is this:
Signals originating/sinking at BP are prefixed with bp_
Signals originating/sinking at c2a are prefixed with c2a_
Normally, this is silly, but since we are optionally adding an intermediate roll of FIFOs, this makes sense to me

2023-01-03 05:41 UTC, mysoreanoop commented on axi/v/bp_axi_top.sv
> -      logic [io_data_width_p-1:0] mem_fwd_data_li, mem_rev_data_lo;
Since inside bp_me_axil_client, the width of mem_fwd_data_o is set to axil_data_width_p, I set it to the same here; this would need to be reflected in bp_unicore also if we're going this way. What do you think?

2023-01-03 06:17 UTC, mysoreanoop commented on axi/v/bp_me_axil_client.sv
> -  `bp_cast_i(bp_bedrock_mem_rev_header_s, mem_rev_header);
was unused

2023-01-05 08:43 UTC, mysoreanoop commented
Requesting review

2023-01-16 04:16 UTC, mysoreanoop commented
@dpetrisko, can we merge this?

2023-03-06 10:25 UTC, mysoreanoop commented on axi/v/bp_axi_top.sv
> +              // TODO these work with the current AXI burst scenario;
outdated

2023-09-29 09:45 UTC, closed without merging

2023-09-29 09:50 UTC, dpetrisko commented on axi/v/bp_axi_top.sv
> +      assign bp_dma_pkt_ready_and_li   = ~c2a_dma_pkt_ready_and_lo; // inverted at source
C2a/BP is fine. The problem is ready=~ready. One of those is actually a full signal and should be named accordingly